# Generated by Django 5.1 on 2024-08-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
