# Generated by Django 5.1 on 2024-08-28 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_speed_alter_review_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creater',
            new_name='Creator',
        ),
    ]
