# Generated by Django 5.1 on 2024-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_creater_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.FloatField(default=400),
        ),
    ]
