# Generated by Django 5.1 on 2024-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_cylinder_fuel_type_car_model_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.FloatField(default=2020),
        ),
    ]
