# Generated by Django 5.1 on 2024-08-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trims',
            new_name='Trim',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.fuel_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cars.trim'),
        ),
    ]
